accounts/urls.py
from django.urls import path
from accounts.views import *
from django.contrib.auth.views import LogoutView
app_name = 'accounts'

urlpatterns = [
    path('login/', Login.as_view(),name = 'login'),
    path('sign/', Register.as_view(),name = 'sign'),
    path('logout/',LogoutView.as_view(),name='logout'),
]

alinino/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import *

app_name = 'core'

urlpatterns = [
    path('', home,name = 'home'),
    path('detail/<int:id>/', detailed_page, name = 'detailed-page'),
    path('filtr/', filtr_page, name = 'filtr-page'),
    path('filtr-rus/', filtr_page_rus, name = 'filtr-page-rus'),
    path('filtr-turk/', filtr_page_turk, name = 'filtr-page-turk'),
    path('filtr-ing/', filtr_page_ing, name = 'filtr-page-ing'),
    path('news/<int:id>/',news_page, name = 'news_page'),
    path('event/<int:id>/',event_page, name = 'event_page'),
    path('club/<int:id>/',club_page, name = 'club_page'),

]

core/models.py
from django.db import models
from accounts.models import *
class News(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="news/")
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    description = models.TextField()
    def __str__(self):
        return self.title

class Tag(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title
class Category(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title




class Product(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="products/")
    description = models.TextField()
    publisher = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=5,decimal_places=2)
    discount_price = models.DecimalField(max_digits=5,decimal_places=2)
    tag = models.ManyToManyField(Tag)
    category = models.ForeignKey("Category",on_delete=models.SET_NULL,related_name='product',db_index=True,null=True,blank=True)

    def __str__(self):
        return self.title

class Club(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="news/")
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    products = models.ManyToManyField(Product)
    description = models.TextField()

    def __str__(self):
        return self.title
class Event(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="event/")
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    description = models.TextField()

    def __str__(self):
        return self.title

class Slider(models.Model):
    image = models.ImageField(upload_to="slide/")
    description = models.TextField()

    def __str__(self):
        return self.description

class Book(models.Model):
    genre = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    language = models.CharField(max_length=100)
    series = models.CharField(max_length=100)

    def __str__(self):
        return self.genre

class Toy(models.Model):
    themes = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    language = models.CharField(max_length=100)
    brend = models.CharField(max_length=100)
    series = models.CharField(max_length=100)
    age = models.CharField(max_length=100)

    def __str__(self):
        return self.themes

class Technique(models.Model):
    themes = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    language = models.CharField(max_length=100)
    brend = models.CharField(max_length=100)
    age = models.CharField(max_length=100)

    def __str__(self):
        return self.themes



class Comment(models.Model):
    user = models.ForeignKey(User,related_name='comments',on_delete=models.SET_NULL,null=True,blank=True)
    product = models.ForeignKey(Product,related_name='comments',on_delete=models.SET_NULL,null=True,blank=True)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
            return self.text

    class Meta:
        ordering = ['-id']

core/forms.py
from django import forms
from core.models import *



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text':forms.Textarea(attrs={'class':'comment-input','rows':'5','placeholder':'Message'})
        }

core/views.py
from django.shortcuts import render
from .models import *
from core.forms import*
def home(request):
    sliders = Slider.objects.all()
    products1 = Product.objects.order_by("-id")[:5]
    products2 = Product.objects.order_by("-id")[5:10]
    az_products1 = Product.objects.filter(category__title="azərbaycan")[:5]
    az_products2 = Product.objects.filter(category__title="azərbaycan")[5:10]
    rus_products1 = Product.objects.filter(category__title="rus")[:5]
    rus_products2 = Product.objects.filter(category__title="rus")[5:10]
    tr_products1 = Product.objects.filter(category__title="türk")[:5]
    tr_products2 = Product.objects.filter(category__title="türk")[5:10]
    ing_products1 = Product.objects.filter(category__title="ingilis")[:5]
    ing_products2 = Product.objects.filter(category__title="ingilis")[5:10]
    comments = Comment.objects.order_by("-id")[:3]
    newss = News.objects.order_by("-id")[:3]
    clubs = Club.objects.order_by("-id")[:3]
    events = Event.objects.order_by("-id")[:3]
    context = {
        'sliders': sliders,
        'products1': products1,
        'products2': products2,
        'az_products1': az_products1,
        'az_products2': az_products2,
        'rus_products1': rus_products1,
        'rus_products2': rus_products2,
        'tr_products1': tr_products1,
        'tr_products2': tr_products2,
        'ing_products1': ing_products1,
        'ing_products2': ing_products2,
        'newss': newss,
        'clubs' : clubs,
        'events': events,
        'comments': comments
    }
    return render(request, 'index.html',context)
   
def detailed_page(request, id):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.product = Product.objects.get(id=id)
            comment.user = request.user
            comment.save()
    form = CommentForm()
    products = Product.objects.get(id=id)
    similar_products = Product.objects.filter()[:5]
    similar_products2 = Product.objects.filter()[5:10]
    context = {
        'form':form,
        'product': products,
        'similar_products': similar_products,
        'similar_products2': similar_products2,
    }
    return render(request, 'detailed-page.html', context)

def filtr_page(request):
    az_products = Product.objects.filter(category__title="azərbaycan")
    search = request.GET.get('search')
    sort = request.GET.get('sort')
    author = request.GET.get('author')
    publisher = request.GET.get('publisher')
    category = request.GET.get('category')
    products = Product.objects.all()
    if author == 'bakixanov':
        az_products = Product.objects.filter(author='Abbasqulu ağa Bakıxanov')
        print(products)
    if author == 'brown':
        az_products = Product.objects.filter(author='Dan Brown')
        print(products)
    if author == 'calil':
        az_products = Product.objects.filter(author='Cəlil Məmmədquluzadə')
        print(products)
        
    
    
        
  
    
    if publisher == 'qanun':
        az_products = Product.objects.filter(publisher='Qanun Nəşriyyatı')
        print(products)
    

    
    
    print(sort)
    if sort == 'new':
        az_products = Product.objects.order_by('-id')
    if sort == 'lower-price':
        az_products = Product.objects.order_by('price')
    if sort == 'higher-price':
        az_products = Product.objects.order_by('-price')
    if sort == 'discount':
        az_products = Product.objects.order_by('discount_price')
    if search:
        az_products = Product.objects.filter(title__icontains=search)
    newss = News.objects.order_by("-id")[:3]

    context = {
        'az_products':az_products,
        'products' : products,
        'newss':newss,
    }
    return render(request, 'filtr-page.html', context)
    


def filtr_page_rus(request):
    rus_products = Product.objects.filter(category__title="rus")
    search = request.GET.get('search')
    sort = request.GET.get('sort')
    author = request.GET.get('author')
    publisher = request.GET.get('publisher')
    category = request.GET.get('category')
    products = Product.objects.all()
    if author == 'carlz':
        rus_products = Product.objects.filter(author='Чарльза Диккенс')
        print(products)
    if author == 'emili':
        rus_products = Product.objects.filter(author='Эмили Баллестерос')
        print(products)
    if author == 'robert':
        rus_products = Product.objects.filter(author='Роберт Луис Стивенсон')
        print(products)
    if author == 'yevqeniy':
        rus_products = Product.objects.filter(author='Евгений Замятин')
        print(products)
        
    
    
        

    
    if publisher == 'eksmo':
        rus_products = Product.objects.filter(publisher='Эксмо')
        print(products)
    if publisher == 'azbuka':
        rus_products = Product.objects.filter(publisher='Азбука')
        print(products)
    if publisher == 'alpina':
        rus_products = Product.objects.filter(publisher='Альпина Паблишер')
        print(products)

    
    
    print(sort)
    if sort == 'new':
        rus_products = Product.objects.order_by('-id')
    if sort == 'lower-price':
        rus_products = Product.objects.order_by('price')
    if sort == 'higher-price':
        rus_products = Product.objects.order_by('-price')
    if sort == 'discount':
        rus_products = Product.objects.order_by('discount_price')
    if search:
        rus_products = Product.objects.filter(title__icontains=search)
    newss = News.objects.order_by("-id")[:3]

    context = {
        'rus_products':rus_products,
        'products' : products,
        'newss':newss,
    }
    return render(request, 'filtr-page-rus.html', context)

def filtr_page_turk(request):
    tr_products = Product.objects.filter(category__title="türk")
    search = request.GET.get('search')
    sort = request.GET.get('sort')
    author = request.GET.get('author')
    publisher = request.GET.get('publisher')
    category = request.GET.get('category')
    products = Product.objects.all()
    if author == 'budak':
        tr_products = Product.objects.filter(author='Beyhan Budak')
        print(products)
    if author == 'rauf':
        tr_products = Product.objects.filter(author='Mehmet Rauf')
        print(products)
    if author == 'wolf':
        tr_products = Product.objects.filter(author='Christa Wolf')
        print(products)
    if author == 'ozgur':
        tr_products = Product.objects.filter(author='Özgür Taburoğlu')
        print(products)
        
    
    
        

    
    if publisher == 'koc':
        tr_products = Product.objects.filter(publisher='Koç Üniversitesi Yayınları')
        print(products)
    if publisher == 'is':
        tr_products = Product.objects.filter(publisher='İş Bankası Kültür Yayınları')
        print(products)
    if publisher == 'kronik':
        tr_products = Product.objects.filter(publisher='Kronik Kitap')
        print(products)

    
    
    print(sort)
    if sort == 'new':
        tr_products = Product.objects.order_by('-id')
    if sort == 'lower-price':
        tr_products = Product.objects.order_by('price')
    if sort == 'higher-price':
        tr_products = Product.objects.order_by('-price')
    if sort == 'discount':
        tr_products = Product.objects.order_by('discount_price')
    if search:
        tr_products = Product.objects.filter(title__icontains=search)
    newss = News.objects.order_by("-id")[:3]

    context = {
        'tr_products':tr_products,
        'products' : products,
        'newss':newss,
    }
    return render(request, 'filtr-page-turk.html', context)

def filtr_page_ing(request):
    ing_products = Product.objects.filter(category__title="ingilis")
    search = request.GET.get('search')
    sort = request.GET.get('sort')
    author = request.GET.get('author')
    publisher = request.GET.get('publisher')
    category = request.GET.get('category')
    products = Product.objects.all()
    if author == 'kawa':
        ing_products = Product.objects.filter(author='Yasunari Kawabata')
        print(products)
    if author == 'susan':
        ing_products = Product.objects.filter(author='Susan Sontag')
        print(products)
    if author == 'marcus':
        ing_products = Product.objects.filter(author='Marcus Aurelius')
        print(products)
    if author == 'bram':
        ing_products = Product.objects.filter(author='Bram Stoker')
        print(products)
        
    
    
        

    
    if publisher == 'arc':
        ing_products = Product.objects.filter(publisher='Arcturus Publishing')
        print(products)
    if publisher == 'ebury':
        ing_products = Product.objects.filter(publisher='Ebury Publishing')
        print(products)
    if publisher == 'penguin':
        ing_products = Product.objects.filter(publisher='Penguin Books Ltd')
        print(products)

    
    
    print(sort)
    if sort == 'new':
        ing_products = Product.objects.order_by('-id')
    if sort == 'lower-price':
        ing_products = Product.objects.order_by('price')
    if sort == 'higher-price':
        ing_products = Product.objects.order_by('-price')
    if sort == 'discount':
        ing_products = Product.objects.order_by('discount_price')
    if search:
        ing_products = Product.objects.filter(title__icontains=search)
    newss = News.objects.order_by("-id")[:3]

    context = {
        'ing_products':ing_products,
        'products' : products,
        'newss':newss,
    }
    return render(request, 'filtr-page-ing.html', context)

def news_page(request,id):
    newsss = News.objects.exclude(id=id).order_by("-id")[:5]

    newss = News.objects.get(id=id)
    context = {
        'newss': newss,
        'newsss': newsss,
    }
    return render(request, 'news.html', context)

def event_page(request,id):
    eventss = Event.objects.exclude(id=id).order_by("-id")[:5]

    events = Event.objects.get(id=id)
    context = {

core/templates/includes/footer.html
<div class="footer">
  <!-- Footer -->
<footer class="text-center text-lg-start bg-body-tertiary text-muted">


  <!-- Section: Links  -->
  <section class="">
    <div class="container">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-4 ">
          <!-- Content -->
           <div class="footer-left">
            <div class="alininologo">
            <img class="footer-logo" src="./img/alininologo.png" alt="">
          </div>
          <div class="footer-contact">
            <div class="footer-number">
              <a href="#">(+99451) 012 34 56</a>
              <p>Telefonla ele indice sifaris edin!</p>
              <a href="#">(+99451) 012 34 56</a>
            
              <a href="#">(+99451) 012 34 56</a>
              
              <button>zeng sifarisi</button>
            </div>
            <div class="footer-email">
              <i class="fa-solid fa-envelope" style="color: #fe0101;"></i>
              <a href="#">info@alinino.az</a>
            </div>
            <div class="footer-clock">
              <i class="fa-regular fa-clock " style="color: #fe0101;"></i>
              <a  href="#">Biz həftənin 7 günü, saat 9:00 - 20:00 qədər çatdırılma edirik.</a>
            </div>
            <div class="footer-whatsapp">
              <i class="fa-brands fa-whatsapp" style="color: #36f793;"></i>
              <a href="#">Whatsapp</a>
            </div>
            

           </div>
           </div>
           
          
          
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 ">
          <!-- Links -->
          <div class="footer-center">
            <h2>Haqqimizda</h2>
            <a href="#">Əlaqə və Ünvanlar</a>
            <a href="#">Xəbərlər</a>
            <a href="#">Bloq</a>
            <a href="#">Bizdən kitab tovsiyyəsi</a>
            <a href="#">"Əli və Nino" nəşriyyatı</a>
            <a href="#">Gizlilik siyasəti</a>
            <a href="#">Sifarişimi qaytarmaq (dəyişmək) istəyirəm</a>
            <a href="#">Pulsuz dənəmə nədir?</a>
            <a href="#">Geyimlərin rahat qaytarılması</a>
            <a href="#">Pulsuz çatdırılma fürsəti</a>
            <a href="#">Sifarişi necə etmək?</a>
            <a href="#">Promokodu necə istifadə etməli?</a>
            <a href="#">Bölgələrdən sifariş etmək qaydası</a>
            <a href="#">"Özün götür" xidməti nədir?</a>
           </div>
        </div>
  
        <div class="col-md-4  footer-right">
          <!-- Links -->
          <h2>Magaza haqqinda</h2>
          <p>Alinino.az saytı</p>
          <p>Alinino.az saytı 15 ildən çoxdur ki, Azərbaycanda operativ satış və çatdırılma xidməti göstərən onlayn satış mağazasıdır.
Azərbaycanın bütün rayon və şəhərlərinə, Bakıda və dünyanın bütün ölkələrindəki bütün ünvanlara çatdırılmanı həyata keçirir. </p>
          <p>Whatsap: (+99451) 312 24 40 <br> Tel: (+99412) 431 40 67" <br>Əli və Nino" Kitab Mağazaları Şəbəkəsi Azərbaycanda 2005-ci ildən fəaliyyət göstərən ən böyük  kitab və oyuncaqlar şəbəkəsidir. <br> Markanın sahibi və icraçı direktoru xanım Nigar Köçərlidir. <br>E-mail: info@alinino.az</p>

          <h2>Sosial şəbəkələrdə biz</h2>
          <i class="fa-brands fa-facebook-f social" style="color: #063c98;"></i>
          <i class="fa-brands fa-instagram social" style="color: #6c22f7;"></i>
          <i class="fa-brands fa-youtube social" style="color: #ff0000;"></i>
          <i class="fa-brands fa-x-twitter social" style="color: black;"></i>
          <i class="fa-brands fa-telegram social" style="color: #3fa2ee;"></i>
          <i class="fa-brands fa-pinterest social" style="color: #ff0000;"></i>
            <div class="qrcodes">
              <div class="android">
            <h6>Android</h6>
            <img class="qrkod" src="./img/qrkodand.png" alt="">
          </div>
          <div class="ios">
            <h6>Apple(iOS)</h6>
            <img class="qrkod" src="./img/Apple.png" alt="">
          </div>
            </div>
          
        </div>
        
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class=" p-4 footer-end" >
    © 2010-2026 Alinino.az. "Ali&Nino" LLC .
    <a class="text-reset fw-bold" href="">Sayt.xeritesi</a> <br>
    hazirlanmisdir. <a class="text-reset fw-bold" href="">ProSales</a> platforma ucun <a class="text-reset fw-bold" href="">InSales</a>

    
  </div>
  <div class="payment">
    <img class="million" src="./img/payment-million.svg" alt="">
    <img class="visa" src="./img/payment-visa.svg" alt="">
    <img class="master" src="./img/payment-mastercard.svg" alt="">
    <img class="mir" src="./img/payment-mir.svg" alt="">

   </div>
  <!-- Copyright -->
   
</footer>
<!-- Footer -->
</div>

core/templates/includes/navbar.html
 {% load static %}
 
    <div class="bottombar">
        <nav class="navbar navbar-light bg-light justify-content-between">
  <a class="navbar-brand" href="{% url 'core:home' %}"><img class="navbar-logo" src="{% static '/img/alinino.png' %}" alt=""></a>

    <div class="input-group mb-6">
      <form action="{% url 'core:filtr-page' %}">
      <input style="width: 300px;" name="search" action="" type="text" class="form-control search-input" placeholder="Kataloq üzrə axtarış" aria-label="Kataloq uzre axtaris " aria-describedby="basic-addon2">
      </form>
  <div class="input-group-append">
    <span class="input-group-text search-btn" id="basic-addon2"><img class="search-icon" src="https://www.freeiconspng.com/uploads/search-icon-png-29.png" alt=""></span>
  </div>
</div>

<div class="profile-icon">
    <div class="container container2">
      <div class="kab" style="display: flex;">

        <i class="fa-solid fa-user user-icon"></i>
        <h5 class="user-title">Şəxsi kabinet</h5>
      </div>
      <div class="middle">
        
        <div class="profile-dropdown2">
      
       {%if request.user.is_authenticated%}
    <div class="top-dropdown">

      <div class="user-info">
      <p class="name-user" style="color: white;">{{ request.user.username }}</p>
      <p class="gmail-user" style="color: WHITE;">{{ request.user.email }}</p>
       
      </div>


    </div>
    <div class="bottom-dropdown">
     
      <form method="post" action="{%url 'accounts:logout'%}">
       
        {% csrf_token %}
        <button type="submit" class="logout-btn">Çıxış</button>
       </form>
    </div>
    {% else %}
    <div class="div">
  <div style="display: flex;" class="profile-dropdown1">
    <a href="{% url 'accounts:login' %}">
      
      <button class="login-btn">Login</button>
    </a>
    <a href="{% url 'accounts:sign' %}">

      <button style="margin-left: 10px;" class="register-btn">Register</button>
    </a>
  </div>
  
</div>

    {% endif %}
  </div>
        
  
  </div>
</div>


</div>
    
  
</nav>
    </div>