accounts/urls.py
from django.urls import path
from accounts.views import *
from django.contrib.auth.views import LogoutView
app_name = 'accounts'

urlpatterns = [
    path('login/', Login.as_view(),name = 'login'),
    path('sign/', Register.as_view(),name = 'sign'),
    path('logout/',LogoutView.as_view(),name='logout'),
]

alinino/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import *

app_name = 'core'

urlpatterns = [
    path('', home,name = 'home'),
    path('detail/<int:id>/', detailed_page, name = 'detailed-page'),
    path('filtr/', filtr_page, name = 'filtr-page'),
    path('filtr-rus/', filtr_page_rus, name = 'filtr-page-rus'),
    path('filtr-turk/', filtr_page_turk, name = 'filtr-page-turk'),
    path('filtr-ing/', filtr_page_ing, name = 'filtr-page-ing'),
    path('news/<int:id>/',news_page, name = 'news_page'),
    path('event/<int:id>/',event_page, name = 'event_page'),
    path('club/<int:id>/',club_page, name = 'club_page'),

]

core/models.py
from django.db import models
from accounts.models import *
class News(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="news/")
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    description = models.TextField()
    def __str__(self):
        return self.title

class Tag(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title
class Category(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title




class Product(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="products/")
    description = models.TextField()
    publisher = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=5,decimal_places=2)
    discount_price = models.DecimalField(max_digits=5,decimal_places=2)
    tag = models.ManyToManyField(Tag)
    category = models.ForeignKey("Category",on_delete=models.SET_NULL,related_name='product',db_index=True,null=True,blank=True)

    def __str__(self):
        return self.title

class Club(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="news/")
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    products = models.ManyToManyField(Product)
    description = models.TextField()

    def __str__(self):
        return self.title
class Event(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="event/")
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    description = models.TextField()

    def __str__(self):
        return self.title

class Slider(models.Model):
    image = models.ImageField(upload_to="slide/")
    description = models.TextField()

    def __str__(self):
        return self.description

class Book(models.Model):
    genre = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    language = models.CharField(max_length=100)
    series = models.CharField(max_length=100)

    def __str__(self):
        return self.genre

class Toy(models.Model):
    themes = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    language = models.CharField(max_length=100)
    brend = models.CharField(max_length=100)
    series = models.CharField(max_length=100)
    age = models.CharField(max_length=100)

    def __str__(self):
        return self.themes

class Technique(models.Model):
    themes = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    language = models.CharField(max_length=100)
    brend = models.CharField(max_length=100)
    age = models.CharField(max_length=100)

    def __str__(self):
        return self.themes



class Comment(models.Model):
    user = models.ForeignKey(User,related_name='comments',on_delete=models.SET_NULL,null=True,blank=True)
    product = models.ForeignKey(Product,related_name='comments',on_delete=models.SET_NULL,null=True,blank=True)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
            return self.text

    class Meta:
        ordering = ['-id']

core/forms.py
from django import forms
from core.models import *



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text':forms.Textarea(attrs={'class':'comment-input','rows':'5','placeholder':'Message'})
        }

core/views.py
from django.shortcuts import render
from .models import *
from core.forms import*
def home(request):
    sliders = Slider.objects.all()
    products1 = Product.objects.order_by("-id")[:5]
    products2 = Product.objects.order_by("-id")[5:10]
    az_products1 = Product.objects.filter(category__title="azərbaycan")[:5]
    az_products2 = Product.objects.filter(category__title="azərbaycan")[5:10]
    rus_products1 = Product.objects.filter(category__title="rus")[:5]
    rus_products2 = Product.objects.filter(category__title="rus")[5:10]
    tr_products1 = Product.objects.filter(category__title="türk")[:5]
    tr_products2 = Product.objects.filter(category__title="türk")[5:10]
    ing_products1 = Product.objects.filter(category__title="ingilis")[:5]
    ing_products2 = Product.objects.filter(category__title="ingilis")[5:10]
    comments = Comment.objects.order_by("-id")[:3]
    newss = News.objects.order_by("-id")[:3]
    clubs = Club.objects.order_by("-id")[:3]
    events = Event.objects.order_by("-id")[:3]
    context = {
        'sliders': sliders,
        'products1': products1,
        'products2': products2,
        'az_products1': az_products1,
        'az_products2': az_products2,
        'rus_products1': rus_products1,
        'rus_products2': rus_products2,
        'tr_products1': tr_products1,
        'tr_products2': tr_products2,
        'ing_products1': ing_products1,
        'ing_products2': ing_products2,
        'newss': newss,
        'clubs' : clubs,
        'events': events,
        'comments': comments
    }
    return render(request, 'index.html',context)
   
def detailed_page(request, id):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.product = Product.objects.get(id=id)
            comment.user = request.user
            comment.save()
    form = CommentForm()
    products = Product.objects.get(id=id)
    similar_products = Product.objects.filter()[:5]
    similar_products2 = Product.objects.filter()[5:10]
    context = {
        'form':form,
        'product': products,
        'similar_products': similar_products,
        'similar_products2': similar_products2,
    }
    return render(request, 'detailed-page.html', context)

def filtr_page(request):
    az_products = Product.objects.filter(category__title="azərbaycan")
    search = request.GET.get('search')
    sort = request.GET.get('sort')
    author = request.GET.get('author')
    publisher = request.GET.get('publisher')
    category = request.GET.get('category')
    products = Product.objects.all()
    if author == 'bakixanov':
        az_products = Product.objects.filter(author='Abbasqulu ağa Bakıxanov')
        print(products)
    if author == 'brown':
        az_products = Product.objects.filter(author='Dan Brown')
        print(products)
    if author == 'calil':
        az_products = Product.objects.filter(author='Cəlil Məmmədquluzadə')
        print(products)
        
    
    
        
  
    
    if publisher == 'qanun':
        az_products = Product.objects.filter(publisher='Qanun Nəşriyyatı')
        print(products)
    

    
    
    print(sort)
    if sort == 'new':
        az_products = Product.objects.order_by('-id')
    if sort == 'lower-price':
        az_products = Product.objects.order_by('price')
    if sort == 'higher-price':
        az_products = Product.objects.order_by('-price')
    if sort == 'discount':
        az_products = Product.objects.order_by('discount_price')
    if search:
        az_products = Product.objects.filter(title__icontains=search)
    newss = News.objects.order_by("-id")[:3]

    context = {
        'az_products':az_products,
        'products' : products,
        'newss':newss,
    }
    return render(request, 'filtr-page.html', context)
    


def filtr_page_rus(request):
    rus_products = Product.objects.filter(category__title="rus")
    search = request.GET.get('search')
    sort = request.GET.get('sort')
    author = request.GET.get('author')
    publisher = request.GET.get('publisher')
    category = request.GET.get('category')
    products = Product.objects.all()
    if author == 'carlz':
        rus_products = Product.objects.filter(author='Чарльза Диккенс')
        print(products)
    if author == 'emili':
        rus_products = Product.objects.filter(author='Эмили Баллестерос')
        print(products)
    if author == 'robert':
        rus_products = Product.objects.filter(author='Роберт Луис Стивенсон')
        print(products)
    if author == 'yevqeniy':
        rus_products = Product.objects.filter(author='Евгений Замятин')
        print(products)
        
    
    
        

    
    if publisher == 'eksmo':
        rus_products = Product.objects.filter(publisher='Эксмо')
        print(products)
    if publisher == 'azbuka':
        rus_products = Product.objects.filter(publisher='Азбука')
        print(products)
    if publisher == 'alpina':
        rus_products = Product.objects.filter(publisher='Альпина Паблишер')
        print(products)

    
    
    print(sort)
    if sort == 'new':
        rus_products = Product.objects.order_by('-id')
    if sort == 'lower-price':
        rus_products = Product.objects.order_by('price')
    if sort == 'higher-price':
        rus_products = Product.objects.order_by('-price')
    if sort == 'discount':
        rus_products = Product.objects.order_by('discount_price')
    if search:
        rus_products = Product.objects.filter(title__icontains=search)
    newss = News.objects.order_by("-id")[:3]

    context = {
        'rus_products':rus_products,
        'products' : products,
        'newss':newss,
    }
    return render(request, 'filtr-page-rus.html', context)

def filtr_page_turk(request):
    tr_products = Product.objects.filter(category__title="türk")
    search = request.GET.get('search')
    sort = request.GET.get('sort')
    author = request.GET.get('author')
    publisher = request.GET.get('publisher')
    category = request.GET.get('category')
    products = Product.objects.all()
    if author == 'budak':
        tr_products = Product.objects.filter(author='Beyhan Budak')
        print(products)
    if author == 'rauf':
        tr_products = Product.objects.filter(author='Mehmet Rauf')
        print(products)
    if author == 'wolf':
        tr_products = Product.objects.filter(author='Christa Wolf')
        print(products)
    if author == 'ozgur':
        tr_products = Product.objects.filter(author='Özgür Taburoğlu')
        print(products)
        
    
    
        

    
    if publisher == 'koc':
        tr_products = Product.objects.filter(publisher='Koç Üniversitesi Yayınları')
        print(products)
    if publisher == 'is':
        tr_products = Product.objects.filter(publisher='İş Bankası Kültür Yayınları')
        print(products)
    if publisher == 'kronik':
        tr_products = Product.objects.filter(publisher='Kronik Kitap')
        print(products)

    
    
    print(sort)
    if sort == 'new':
        tr_products = Product.objects.order_by('-id')
    if sort == 'lower-price':
        tr_products = Product.objects.order_by('price')
    if sort == 'higher-price':
        tr_products = Product.objects.order_by('-price')
    if sort == 'discount':
        tr_products = Product.objects.order_by('discount_price')
    if search:
        tr_products = Product.objects.filter(title__icontains=search)
    newss = News.objects.order_by("-id")[:3]

    context = {
        'tr_products':tr_products,
        'products' : products,
        'newss':newss,
    }
    return render(request, 'filtr-page-turk.html', context)

def filtr_page_ing(request):
    ing_products = Product.objects.filter(category__title="ingilis")
    search = request.GET.get('search')
    sort = request.GET.get('sort')
    author = request.GET.get('author')
    publisher = request.GET.get('publisher')
    category = request.GET.get('category')
    products = Product.objects.all()
    if author == 'kawa':
        ing_products = Product.objects.filter(author='Yasunari Kawabata')
        print(products)
    if author == 'susan':
        ing_products = Product.objects.filter(author='Susan Sontag')
        print(products)
    if author == 'marcus':
        ing_products = Product.objects.filter(author='Marcus Aurelius')
        print(products)
    if author == 'bram':
        ing_products = Product.objects.filter(author='Bram Stoker')
        print(products)
        
    
    
        

    
    if publisher == 'arc':
        ing_products = Product.objects.filter(publisher='Arcturus Publishing')
        print(products)
    if publisher == 'ebury':
        ing_products = Product.objects.filter(publisher='Ebury Publishing')
        print(products)
    if publisher == 'penguin':
        ing_products = Product.objects.filter(publisher='Penguin Books Ltd')
        print(products)

    
    
    print(sort)
    if sort == 'new':
        ing_products = Product.objects.order_by('-id')
    if sort == 'lower-price':
        ing_products = Product.objects.order_by('price')
    if sort == 'higher-price':
        ing_products = Product.objects.order_by('-price')
    if sort == 'discount':
        ing_products = Product.objects.order_by('discount_price')
    if search:
        ing_products = Product.objects.filter(title__icontains=search)
    newss = News.objects.order_by("-id")[:3]

    context = {
        'ing_products':ing_products,
        'products' : products,
        'newss':newss,
    }
    return render(request, 'filtr-page-ing.html', context)

def news_page(request,id):
    newsss = News.objects.exclude(id=id).order_by("-id")[:5]

    newss = News.objects.get(id=id)
    context = {
        'newss': newss,
        'newsss': newsss,
    }
    return render(request, 'news.html', context)

def event_page(request,id):
    eventss = Event.objects.exclude(id=id).order_by("-id")[:5]

    events = Event.objects.get(id=id)
    context = {

core/templates/club.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <div class="breadcrumb-items">
    <li class="breadcrumb-item"><a class="breadcrumb-home" href="{% url 'core:home' %}">Əsas</a></li>
    <li class="breadcrumb-item " aria-current="page">Tədbirlər</li>
  </ol>
  </div>
</nav>
    <div class="news-page">
     
        <div class="news-date">
                        <p class="date">{{clubs.date|date:"d.m.Y"}}</p>

        </div>
        <h1 class="news-page-title">{{clubs.title}}</h1>
        <div class="">
            <p class="news-page-text">{{ clubs.text }}</p>
            <img src="{{clubs.image.url}}" alt="">
        </div>
        
      
        <h1 class="news-page-title">Digər paylaşımlar</h1>
        <div style="max-width: fit-content;margin-right: 100px;" class="container">
          <div class="row">

        {% for club in clubss %}
        <div class="col-md-4">
        <div class="other-posts">
  <div class="news-card news2">
    <div class="new-div">
    <a href="{% url 'core:club_page' club.id%}">
      <img class="news-img" src="{{club.image.url}}" alt="">
      <div class="news-text">
      <h5 class="news-title">{{club.title}}</h5>
      <p class="news-description"> {{club.text}}</p>
      </div>

    </a>
     </div>
  </div>
  
        </div>
        </div>
        {% endfor %}
        </div>
        </div>
    </div>

{% endblock %}

core/templates/events.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <div class="breadcrumb-items">
    <li class="breadcrumb-item"><a class="breadcrumb-home" href="{% url 'core:home' %}">Əsas</a></li>
    <li class="breadcrumb-item " aria-current="page">Tədbirlər</li>
  </ol>
  </div>
</nav>
    <div class="news-page">
     
        <div class="news-date">
               <p class="date">{{events.date|date:"d.m.Y"}}</p>

        </div>
        <h1 class="news-page-title">{{events.title}}</h1>
        <div class="">
            <p class="news-page-text">{{ events.description }}</p>
            <img src="{{events.image.url}}" alt="">
        </div>
        
      
        <h1 class="news-page-title">Digər paylaşımlar</h1>
        <div style="max-width: fit-content;margin-right: 100px;" class="container">
          <div class="row">

        {% for event in eventss %}
        <div class="col-md-4">
        <div class="other-posts">
  <div class="news-card news2">
    <div class="new-div">
    <a href="{% url 'core:event_page' event.id%}">
      <img class="news-img" src="{{event.image.url}}" alt="">
      <div class="news-text">
      <h5 class="news-title">{{event.title}}</h5>
      <p class="news-description"> {{event.text}}</p>
      </div>

    </a>
     </div>
  </div>
  
        </div>
        </div>
        {% endfor %}
        </div>
        </div>
    </div>

{% endblock %}

core/templates/filtr-page-ing.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <div class="breadcrumb-items">
    <li class="breadcrumb-item"><a class="breadcrumb-home" href="{% url 'core:home' %}">Əsas</a></li>
    <li class="breadcrumb-item " aria-current="page">Kataloq</li>
  </ol>
  </div>
</nav>
     <div class="collapse-title">
            <h4 class="category-title">Yeni İngilis nəşrləri</h4>
            <p class="quantity">{{ing_products.count}} məhsul</p>
        </div>
        <div class="filtr-page">
    <div class="part1 filter">
       <a class="category-name" href="#">Yeni İngilis nəşrləri</a>
       <br>
       <div class="filtr-card">
        
       
       <a class="filter-item" href="#">Mövcud olan məhsullar</a>
       
        <a class="filter-item" href="#">Qiymət,  AZN</a>

       <div class="accordion" id="accordionExample">
  
  <div class="card">
    <div class="card-header" id="headingTwo">
      <h2 class="mb-0">
        <button class="btn btn2 btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          Müəllif
        </button>
      </h2>
    </div>

    <div id="collapseTwo" class="collapse show" aria-labelledby="headingTwo" data-parent="#accordionExample">
      <div class="card-body">
        <div class="form-check">
  <a href="?author=kawa"><input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
  <label class="form-check-label" >
    Yasunari Kawabata
  </label></a>
</div>
        <div class="form-check">
  <a href="?author=susan"><input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
  <label class="form-check-label" >
    Susan Sontag
  </label></a>
</div>
        <div class="form-check">
  <a href="?author=marcus"><input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
  <label class="form-check-label" >
    Marcus Aurelius
  </label></a>
</div>
<div class="form-check">
  <a href="?author=bram"><input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
  <label class="form-check-label" >
    Bram Stoker
  </label></a>
</div>
       

        

      </div>
    </div>
  </div>
  <!-- <div class="card">
    <div class="card-header" id="heading3">
      <h2 class="mb-0">
        <button class="btn btn2 btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapse3" aria-expanded="true" aria-controls="collapse3">
          Dil
        </button>
      </h2>
    </div>

    <div id="collapse3" class="collapse show" aria-labelledby="heading3" data-parent="#accordionExample">
      <div class="card-body">
        <div class="form-check">
  <a href="?category=rus"><input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
  <label class="form-check-label" >
    rus
  </label></a>
</div>

      </div>
    </div>
  </div> -->
  <div class="card">
    <div class="card-header" id="heading4">
      <h2 class="mb-0">
        <button class="btn btn2 btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapse4" aria-expanded="true" aria-controls="collapse4">
          Nəşriyyatçı
        </button>
      </h2>
    </div>

    <div id="collapse4" class="collapse show" aria-labelledby="heading4" data-parent="#accordionExample">
      <div class="card-body">
       <div class="form-check">
  <a href="?publisher=arc"><input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
  <label class="form-check-label" >
    Arcturus Publishing
  </label></a>
</div>
      <div class="form-check">
  <a href="?publisher=ebury"><input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
  <label class="form-check-label" >
    Ebury Publishing
  </label></a>
</div>

      <div class="form-check">
  <a href="?publisher=penguin"><input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
  <label class="form-check-label" >
    Penguin Books Ltd
  </label></a>
</div>

      </div>
    </div>
  </div>


</div>
  </div>
  {% for news in newss %}
  <div class="news-rc">
    
    <div class="article">
      <a class="news-a" href="{% url 'core:news_page' news.id%}">
        <img src="{{news.image.url}}" alt="">
        <h6>{{news.title}}</h6>
        <p>{{news.text}} </p>
      </a>
    </div>
  </div>
  {% endfor %}
    </div>
    {% if ing_products %}
    <div class="part2">
      
<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sirala
        </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'core:filtr-page-ing'%}?sort=new">Yeniliklər</a>
          <a class="dropdown-item" href="{% url 'core:filtr-page-ing'%}?sort=lower-price">Öncə aşağı qiymət</a>
          <a class="dropdown-item" href="{% url 'core:filtr-page-ing'%}?sort=higher-price">Öncə yüksək qiymət</a>
          <a class="dropdown-item" href="{% url 'core:filtr-page-ing'%}?sort=discount">Endirim məbləği ilə</a>
        </div>

<div class="products">
  <div class="container">
    <div class="row">
 {% for product in ing_products %}
      <div class="col-md-3">
        <a class="product-a" href="{% url 'core:detailed-page' product.id%}">
    <div class="book1">  
    <div class="books-list">
        <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{ product.image.url }}" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{ product.price }} AZN
    <span style="text-decoration: line-through;" class="sale-price">{{ product.discount_price}}AZN</span></h5>
    <p class="card-text">{{ product.title }}</p>
    <div class="rating">
  <i  class="fa-solid fa-star rate-star"></i>
   <i  class="fa-solid fa-star rate-star"></i>
    <i  class="fa-solid fa-star rate-star"></i>
     <i  class="fa-solid fa-star rate-star"></i>
      <i  class="fa-solid fa-star rate-star"></i>
      <i class="fa-solid fa-comment comment-icon">{{product.comments.all.count}}</i>
</div>


    </div>
    
  </div>
</div>
    </div>
     </a>
      </div>
        {% endfor %}
    </div>
  </div>
 
  

     </div>



<div class="filtr-text" id="learn-more-div">
  <h4>  Bakıda ingilis dilində yeni kitabları Alinino.az saytından sifariş edin!</h4>
  <p>Bizim onlayn mağazamızda turk dilində yeni çap olunan bütün kitabları endirimli qiymətlə sifariş etmək mümkündür.</p>
  <p>Turk dilində klassika, biznes kitabları, psixologiya və şəxsi inkişaf kitabları, detektiv romanlar və digər yüzlərlə yeni kitabı evdən çıxmadan <br> məhz Alinino.az online mağazasından çatdırılma ilə əldə edə bilərsiniz.</p>
   <h4>Yeni kitabları niyə mütləq oxumalıyıq?</h4>
  <p> Yeni kitablar oxumaq bir çox fayda verə bilər. Yeni kitablar oxumağın bəzi müsbət təsirləri bunlardır:</p>
  <p>Biliyin genişləndirilməsi: Yeni kitablar sizə müxtəlif mövzular haqqında məlumat əldə etməyə imkan verir. Bu, özünüzü təkmilləşdirmək və daha çox bilik əldə etmək üçün əla bir yol ola bilər.</p>
  <p>Düşüncə qabiliyyətinin inkişafı: Yeni kitablar müxtəlif perspektivləri və düşüncə tərzini kəşf etməyə kömək edə bilər. Bu, düşünmə qabiliyyətinizi artıra bilər.</p>
  <p>Söz bazasının genişləndirilməsi: Yeni kitablar oxuyarkən yeni sözlər öyrənmək imkanınız ola bilər. Bu, söz ehtiyatınızı zənginləşdirir və ünsiyyət bacarıqlarınızı artırır.</p>
  <p>Empatiyanın inkişafı: Romanlar və hekayələr müxtəlif personajların həyatını anlamaq imkanı verir. Bu, empatiyanızı yaxşılaşdırır və insan münasibətlərinizdə daha anlayışlı olmağa kömək edə bilər.</p>  
  <p>Diqqətin inkişafı: Kitab oxumaq diqqət və diqqət bacarıqlarını inkişaf etdirə bilər. Bir kitabı bitirmək üçün uzun müddət diqqətinizə ehtiyacınız ola bilər.</p>
  <p>Əyləncə və həzz: Yeni kitablar oxumaq təkcə faydalı deyil, həm də zövqlü ola bilər. Yaxşı bir kitab sizi müxtəlif dünyalara daşıya bilər və darıxdırıcı vaxtları daha maraqlı edə bilər.</p>
  <p>Artan Yaradıcılıq: Xüsusilə bədii əsərlər sizin təxəyyülünüzü və yaradıcılığınızı stimullaşdıra bilər. Hekayələr və personajlar öz düşüncənizi genişləndirməyə kömək edə bilər.</p>
  <p>Mənəvi İnkişaf: Bəzi kitablar şəxsi inkişaf və mənəvi inkişafla bağlı təlimat verə bilər. Bu tip kitablar özünüzü daha yaxşı başa düşməyə və həyatınızı yaxşılaşdırmağa kömək edə bilər</p>
  <p>Düşüncə müxtəlifliyi: Fərqli yazıçıların fərqli düşüncə tərzi və perspektivləri var. Buna görə də, yeni kitablar oxumaq düşüncə müxtəlifliyini təşviq edir və zəngin intellektual təcrübə təmin edir</p>



<p>
  <button class="btn btn-primary more2" id="dont-learn-more" onclick="dontLearnMore()">
    Bağla
</button>
</p>

</div>
<button class="btn btn-primary more ml-4" id="learn-more" onclick="learnMore()">
    Daha ətraflı oxuyun
</button>

    </div>
     {% else %}
    <div class="filtr-text" id="learn-more-div">
      <h4>Təəssüf hazırda axtardığınız kitab yoxdur</h4>
      {% endif %}
        </div>
        </div>
{% endblock %}
    









   